

logging.file: logs/application.log
logging:
  level:
      org:
        springframework:
          web: DEBUG
        hibernate: DEBUG

server:
  port : 8888

spring:
  datasource:
    url:  jdbc:h2:file:./h2/org
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true